In [1]:
import numpy as np

arr = np.array([20, 2, 10, 9])
print(type(arr))

print(arr + 1)
print(arr * 2)

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

list1 = [20, 2, 10, 9]
# print(list1 + 1)
print(list1 * 2)

print(np.sort(arr))
print(np.unique(arr))

<class 'numpy.ndarray'>
[21  3 11 10]
[40  4 20 18]
41
10.25
9.5
6.417748826496718
41.1875
2
20
[20, 2, 10, 9, 20, 2, 10, 9]
[ 2  9 10 20]
[ 2  9 10 20]


In [2]:
# 2d array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(arr2d))
print(arr2d[0])
print(arr2d[2])

<class 'numpy.ndarray'>
[1 2 3]
[7 8 9]
